import { useRouter } from "next/router";
import Head from "next/head";

import { Box, Heading } from "@chakra-ui/react";

import CreateRequestForm from "../../../../components/forms/CreateRequestForm";

const CreateRequestPage = () => {
  const router = useRouter();
  const { address } = router.query;

  return (
    <>
      <Head>
        <title>Starlit Crowdfunding | new request</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h1" mb={4}>
        New Request: Campaign {address}
      </Heading>
      <Box>
        <CreateRequestForm />
      </Box>
    </>
  );
};

export default CreateRequestPage;
