import { useRouter } from "next/router";
import Head from "next/head";

import { Box, Heading } from "@chakra-ui/react";

import CreateTerminationForm from "../../../../components/forms/CreateTerminationForm";

const CreateTerminationPage = () => {
  const router = useRouter();
  const { address } = router.query;

  return (
    <>
      <Head>
        <title>Starlit Crowdfunding | New Termination Request</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h1" mb={4}>
        Termination Request: Campaign {address}
      </Heading>
      <Box>
        <CreateTerminationForm />
      </Box>
    </>
  );
};

export default CreateTerminationPage;
