import Head from "next/head";
import { Container, Heading } from "@chakra-ui/react";

import CreateCampaignForm from "../../components/forms/CreateCampaignForm";

export default function NewCampaign() {
  return (
    <Container>
      <Head>
        <title>Starlit Crowdfunding | new</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading as="h1">Create New Campaign</Heading>

      <CreateCampaignForm />
    </Container>
  );
}
