import Head from "next/head";
import Image from "next/image";
import NextLink from "next/link";
import styles from "../styles/Home.module.css";

import { useEffect, useState } from "react";

import {
  Box,
  Center,
  Container,
  Heading,
  SimpleGrid,
  Button,
  Flex,
} from "@chakra-ui/react";
import CampaignCard from "../components/card/CampaignCard";
import CampaignSearch from "../components/search/CampaignSearch";

export default function Home() {
  const [campaign, setCampaign] = useState([]);
  useEffect(() => {
    fetch("/api/campaign")
      .then((response) => response.json())
      .then((data) => setCampaign(data));
  }, []);

  const renderCampaignList = () => {
    return campaign.map((c) => (
      <CampaignCard key={c.address} address={c.address} />
    ));
  };

  return (
    <Container maxWidth="container.xl" p={2}>
      <Head>
        <title>Starlit Crowdfunding | main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box my={8}>
        <Flex justify="space-between" alignItems="center">
          <Heading size="md">Running Campaigns</Heading>
          <NextLink href="/campaign/new">
            <Button>Create</Button>
          </NextLink>
        </Flex>
        <CampaignSearch />
        <SimpleGrid columns={[1, null, null, 2]} spacing="4">
          {renderCampaignList()}
        </SimpleGrid>
      </Box>
    </Container>
  );
}
